/**
 * Storage keys are generated by the server — never taken from a user — and look like
 * `companies/<companyId>/logo/<uuid>.png`. Validation still guards against path traversal.
 */
const KEY_PATTERN = /^[a-z0-9][a-z0-9/_.-]{0,500}$/i;

export function assertValidKey(key: string): void {
  if (!KEY_PATTERN.test(key) || key.includes("..") || key.includes("//") || key.endsWith("/")) {
    throw new Error(`Invalid storage key: ${JSON.stringify(key)}`);
  }
}

/** Every tenant file lives under its company's prefix, so keys themselves carry the tenant boundary. */
export function companyKey(companyId: string, ...parts: string[]): string {
  const key = ["companies", companyId, ...parts].join("/");
  assertValidKey(key);
  return key;
}
