import {
  ArrowLeftRight,
  BookOpen,
  FileBarChart,
  Receipt,
  Bell,
  BriefcaseBusiness,
  ChartColumn,
  ClipboardCheck,
  FileText,
  HandCoins,
  FolderKanban,
  LayoutDashboard,
  Package,
  ReceiptText,
  ScrollText,
  Settings,
  ShieldCheck,
  Target,
  UserCog,
  Users,
  Wallet,
  WalletCards,
  type LucideIcon,
} from "lucide-react";
import type { NavIconName } from "@/config/navigation";

/** Icon component for each navigation icon name. */
export const NAV_ICONS: Record<NavIconName, LucideIcon> = {
  dashboard: LayoutDashboard,
  customers: Users,
  leads: Target,
  quotations: FileText,
  orders: ClipboardCheck,
  payments: HandCoins,
  expenses: Receipt,
  accounts: BookOpen,
  transactions: ArrowLeftRight,
  statements: FileBarChart,
  sales: ReceiptText,
  finance: Wallet,
  hr: BriefcaseBusiness,
  payroll: WalletCards,
  projects: FolderKanban,
  inventory: Package,
  reports: ChartColumn,
  users: UserCog,
  roles: ShieldCheck,
  audit: ScrollText,
  settings: Settings,
  notifications: Bell,
};
