import {
  ArrowLeftRight,
  BookOpen,
  FileBarChart,
  Receipt,
  Bell,
  Banknote,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  CalendarDays,
  IdCard,
  ChartColumn,
  ClipboardCheck,
  FileText,
  HandCoins,
  FolderKanban,
  LayoutDashboard,
  ListChecks,
  Package,
  ReceiptText,
  ScrollText,
  Settings,
  ShieldCheck,
  SquareKanban,
  Target,
  UserCog,
  Users,
  Wallet,
  WalletCards,
  type LucideIcon,
} from "lucide-react";
import type { NavIconName } from "@/config/navigation";

/** Icon component for each navigation icon name. */
export const NAV_ICONS: Record<NavIconName, LucideIcon> = {
  dashboard: LayoutDashboard,
  customers: Users,
  leads: Target,
  quotations: FileText,
  orders: ClipboardCheck,
  payments: HandCoins,
  expenses: Receipt,
  accounts: BookOpen,
  transactions: ArrowLeftRight,
  statements: FileBarChart,
  sales: ReceiptText,
  finance: Wallet,
  hr: BriefcaseBusiness,
  employees: IdCard,
  departments: Building2,
  attendance: CalendarClock,
  leave: CalendarDays,
  payroll: WalletCards,
  advances: Banknote,
  projects: FolderKanban,
  tasks: ListChecks,
  board: SquareKanban,
  inventory: Package,
  reports: ChartColumn,
  users: UserCog,
  roles: ShieldCheck,
  audit: ScrollText,
  settings: Settings,
  notifications: Bell,
};
